//Login
export const ADD_LOGIN = "ADD_LOGIN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

//EREWARDZ
export const EREWARDZ_SET_DATA = "EREWARDZ_SET_DATA";
export const EREWARDZ_FAIL_DATA = "EREWARDZ_FAIL_DATA";
export const EREWARDZ_LOADING = "EREWARDZ_LOADING";

//POWERUSERS
export const POWERUSERS_SET_DATA = "POWERUSERS_SET_DATA";
export const POWERUSERS_FAIL_DATA = "POWERUSERS_FAIL_DATA";
export const POWERUSERS_LOADING = "POWERUSERS_LOADING";

//SEPTUSERS
export const SEPTUSERS_SET_DATA = "SEPTUSERS_SET_DATA";
export const SEPTUSERS_FAIL_DATA = "SEPTUSERS_FAIL_DATA";
export const SEPTUSERS_LOADING = "SEPTUSERS_LOADING";

//TTP
export const TTP_SET_DATA = "TTP_SET_DATA";
export const TTP_FAIL_DATA = "TTP_FAIL_DATA";
export const TTP_LOADING = "TTP_LOADING";

//rise users
export const RISE_USERS_SET_DATA = "RISE_USERS_SET_DATA";
export const RISE_USERS_FAIL_DATA = "RISE_USERS_FAIL_DATA";
export const RISE_USERS_LOADING = "RISE_USERS_LOADING";

//rise users-2
export const RISE_USERS_2_SET_DATA = "RISE_USERS_2_SET_DATA";
export const RISE_USERS_2_FAIL_DATA = "RISE_USERS_2_FAIL_DATA";
export const RISE_USERS_2_LOADING = "RISE_USERS_2_LOADING";

//*Lap users
export const LAP_USERS_SET_DATA = "LAP_USERS_SET_DATA";
export const LAP_USERS_FAIL_DATA = "LAP_USERS_FAIL_DATA";
export const LAP_USERS_LOADING = "LAP_USERS_LOADING";

//*White Users
export const WHITE_USERS_SET_DATA = "WHITE_USERS_SET_DATA";
export const WHITE_USERS_FAIL_DATA = "WHITE_USERS_FAIL_DATA";
export const WHITE_USERS_LOADING = "WHITE_USERS_LOADING";

//gimaestro-users
export const GIMASTRO_SET_DATA = "GIMASTRO_SET_DATA";
export const GIMASTRO_FAIL_DATA = "GIMASTRO_FAIL_DATA";
export const GIMASTRO_LOADING = "GIMASTRO_LOADING";

//aug-impact-pro-users
export const AUG_PRO_SET_DATA = "AUG_PRO_SET_DATA";
export const AUG_PRO_FAIL_DATA = "AUG_PRO_FAIL_DATA";
export const AUG_PRO_LOADING = "AUG_PRO_LOADING";

//sep-impact-pro-users
export const SEP_PRO_SET_DATA = "   SEP_PRO_SET_DATA";
export const SEP_PRO_FAIL_DATA = "  SEP_PRO_FAIL_DATA";
export const SEP_PRO_LOADING = "    SEP_PRO_LOADING";
